#!/usr/bin/env bash

pushd /opt/graphite

export DJANGO_SETTINGS_MODULE=graphite.settings

python /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/bin/django-admin.py syncdb
sudo python bin/carbon-cache.py start
sudo python bin/run-graphite-devel-server.py ./

popd
./graphite_end
